name: Publish-on-Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm ci --ignore-scripts
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
